[platformio]
default_envs = minimaluart-stm32f405

[env:minimaluart-stm32f405]
platform = native
platform_packages = platformio/tool-openocd
extra_scripts = post:platformio_upload.py
monitor_speed = 115200

; Flash the image produced by the F' build rather than rebuilding under
; PlatformIO.
custom_fprime_bin = build-minimaluart-image/bin/arm-gcc-stm32/STM32MinimalUart.bin
custom_fprime_elf = build-minimaluart-image/bin/arm-gcc-stm32/STM32MinimalUart.elf
custom_openocd_interface = interface/stlink.cfg
custom_openocd_target = target/stm32f4x.cfg
custom_touch_port = /dev/ttyACM0
custom_dfu_vidpid = 0x0483:0xDF11
custom_dfu_address = 0x08000000
